spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/kaitechcrm
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver


  flyway:
    enabled: true
    baseline-on-migrate: true
    locations:
      - classpath:db/migration
    url: jdbc:postgresql://localhost:5432/kaitechcrm
    user: postgres
    password: postgres
    default-schema: kaitech