spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/kaitechcrm
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver


security:
  jwt:
    secret: ASDASJOPASJPDAJoasasdiasjdsaio21312ajdasojdasojdoiASDAS
    access: 1
    refresh: 30