spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 123asdf
    driver-class-name: org.postgresql.Driver


  flyway:
    enabled: true
    baseline-on-migrate: true
    locations:
      - classpath:db/migration
    url: jdbc:postgresql://localhost:5432/postgres
    user: postgres
    password: 123asdf
    default-schema: public

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true

server:
  port: ${PORT:8080}