spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/kaitechcrm
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

security:
  jwt:
    secret: SecretSecretAmanZholdoshovAzimzhanovErZhAn2003
    access: 1
    refresh: 30
