CREATE TABLE if not exists courses
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    course_name        VARCHAR(255),
    cost               INTEGER,
    duration_in_months INTEGER,
    description        VARCHAR(255),
    image_url          VARCHAR(255),
    status             VARCHAR(255),
    number_of_lessons  INTEGER,
    CONSTRAINT pk_courses PRIMARY KEY (id)
);

CREATE TABLE if not exists groups
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    group_name   VARCHAR(255),
    course_id    BIGINT,
    mentor_id    BIGINT,
    max_capacity INTEGER,
    start_date   date,
    end_date     date,
    status       VARCHAR(255),
    image_url    VARCHAR(255),
    days         VARCHAR(255),
    start_time   time WITHOUT TIME ZONE,
    end_time     time WITHOUT TIME ZONE,
    CONSTRAINT pk_groups PRIMARY KEY (id)
);

CREATE TABLE if not exists mentors
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email        VARCHAR(255),
    full_name    VARCHAR(255),
    phone_number VARCHAR(255),
    salary       INTEGER,
    status       VARCHAR(255),
    course_id    BIGINT,
    image_url    VARCHAR(255),
    CONSTRAINT pk_mentors PRIMARY KEY (id)
);

CREATE TABLE if not exists payment
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    student_id   BIGINT,
    sum          INTEGER,
    date         date,
    payment_type SMALLINT,
    CONSTRAINT pk_payment PRIMARY KEY (id)
);

CREATE TABLE if not exists students
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    full_name    VARCHAR(255),
    email         VARCHAR(255),
    phone_number  VARCHAR(255),
    status        VARCHAR(255),
    group_id      BIGINT,
    date_of_birth TIMESTAMP WITHOUT TIME ZONE,
    gender        VARCHAR(255),
    total_debt    DECIMAL,
    total_payment DECIMAL,
    CONSTRAINT pk_students PRIMARY KEY (id)
);

CREATE TABLE if not exists users
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    first_name      VARCHAR(255),
    last_name       VARCHAR(255),
    date_of_birth   date,
    phone_number    VARCHAR(255),
    email           VARCHAR(255),
    password        VARCHAR(255),
    role            VARCHAR(255),
    enabled         BOOLEAN,
    image_url       VARCHAR(255),
    last_visit_date TIMESTAMP WITHOUT TIME ZONE,
    status          VARCHAR(255),
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE groups
    ADD CONSTRAINT FK_GROUPS_ON_COURSE FOREIGN KEY (course_id) REFERENCES courses (id);

ALTER TABLE groups
    ADD CONSTRAINT FK_GROUPS_ON_MENTOR FOREIGN KEY (mentor_id) REFERENCES mentors (id);

ALTER TABLE mentors
    ADD CONSTRAINT FK_MENTORS_ON_COURSE FOREIGN KEY (course_id) REFERENCES courses (id);

ALTER TABLE payment
    ADD CONSTRAINT FK_PAYMENT_ON_STUDENT FOREIGN KEY (student_id) REFERENCES students (id);

ALTER TABLE students
    ADD CONSTRAINT FK_STUDENTS_ON_GROUP FOREIGN KEY (group_id) REFERENCES groups (id);